require_relative '../node_modules/react-native/scripts/react_native_pods.rb'

platform :ios, '15.1'

# Firebase Swift pods fix + avoid PromisesObjC header errors
use_frameworks! :linkage => :static     # ← IMPORTANT FIX

install! 'cocoapods',
  :deterministic_uuids => false

target 'Upkyc' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true
  )

  # Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/RemoteConfig'

  pod 'nanopb'
  pod 'ZIPFoundation'

  post_install do |installer|
    react_native_post_install(installer, :mac_catalyst_enabled => false)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['DEFINES_MODULE'] = 'YES'
        config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      end
    end
  end
end
