require_relative '../node_modules/react-native/scripts/react_native_pods.rb'

platform :ios, '15.1'

install! 'cocoapods',
  :deterministic_uuids => false

target 'Upkyc' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true
  )

  # Firebase + Swift pods that MUST use modular headers
  pod 'GoogleUtilities', :modular_headers => true
  pod 'GoogleDataTransport', :modular_headers => true

  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'FirebaseInstallations', :modular_headers => true

  pod 'FirebaseCrashlytics', :modular_headers => true
  pod 'FirebaseRemoteConfig', :modular_headers => true
  pod 'FirebaseAnalytics', :modular_headers => true
  pod 'FirebaseABTesting', :modular_headers => true
  pod 'FirebaseSessions', :modular_headers => true

  # nanopb must generate a module map
  pod 'nanopb', :modular_headers => true

  # --- Fix nanopb static build ---
  pre_install do |installer|
    installer.pod_targets.each do |pod|
      if pod.name == 'nanopb'
        def pod.build_type
          Pod::BuildType.static_library
        end
      end
    end
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      :mac_catalyst_enabled => false
    )

    # Ensure correct dSYM generation including Hermes
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
      end
    end
  end
end
